version: '3.0'
volumes:
  go-pkg:

services:
  pingr:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        UID: ${UID}
    sysctls:
      - net.ipv4.ping_group_range=0 2147483647
    environment:
      DEV: |-
        true
      BASE_URL: "http://localhost:8080"
      BASIC_AUTH_USER: "dev"
      BASIC_AUTH_PASS: "123abc"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_USERNAME: "pingrman@gmail.com"
      SMTP_PASSWORD: "2KPy8WJr2uLC46g"
      AES_KEY: "6368616e676520746869732070617373776f726420746f206120736563726574"
    ports:
    - "8080:8080"
    volumes:
      - go-pkg:/go/pkg
      - .:/go/src/pingr

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui.dev
      args:
        UID: ${UID}
    environment:
      DEV: |-
        true
    ports:
      - "8081:8081"
#      - "8080:8080"
    volumes:
      - ./ui:/ui